### ISSUE TITLE
npm start triggers error, exist status 1 failed at start script

### ISSUE THREAD

**Issue by Syntaf** [christophior/JSONConfigurablePersonalSite#5]
I installed the latest npm by grabbing the latest [node](https://nodejs.org/en/) release. Then I did the following:

```
git clone git@github.com:christophior/JSONConfigurablePersonalSite
cd JSONConfigurablePersonalSite
npm install
npm start
```

And this error printed:

```
> JSONConfigurablePersonalSite@1.0.0 start /home/gdev-home/Github/JSONConfigurablePersonalSite
> node app.js


npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! JSONConfigurablePersonalSite@1.0.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the JSONConfigurablePersonalSite@1.0.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the JSONConfigurablePersonalSite package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls JSONConfigurablePersonalSite
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/gdev-home/Github/JSONConfigurablePersonalSite/npm-debug.log
```

here's `npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.14.7
3 info using node@v4.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart JSONConfigurablePersonalSite@1.0.0
6 info start JSONConfigurablePersonalSite@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info JSONConfigurablePersonalSite@1.0.0 Failed to exec start script
9 verbose stack Error: JSONConfigurablePersonalSite@1.0.0 start: `node app.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid JSONConfigurablePersonalSite@1.0.0
11 verbose cwd /home/gdev-home/Github/JSONConfigurablePersonalSite
12 error Linux 3.13.0-65-generic
13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
14 error node v4.2.1
15 error npm  v2.14.7
16 error code ELIFECYCLE
17 error JSONConfigurablePersonalSite@1.0.0 start: `node app.js`
17 error Exit status 1
18 error Failed at the JSONConfigurablePersonalSite@1.0.0 start script 'node app.js'.
18 error This is most likely a problem with the JSONConfigurablePersonalSite package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node app.js
18 error You can get their info via:
18 error     npm owner ls JSONConfigurablePersonalSite
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

Any ideas what i'm doing wrong?

**Comment by christophior** [comment]
I'll try reproducing this with the current release of node and npm. I checked my local machine and i'm running node v0.12.7 and npm 2.11.3.

**Comment by christophior** [comment]
Did a quick install using the latest node/npm versions and everything looks fine for me. I'll comment any other findings.

**Comment by christophior** [comment]
Can you please try running 'node app.js'

**Comment by Syntaf** [comment]
Looks like what happened was my npm install wasn't setup correctly, after doing a fresh re-install it works great. Sorry for the confusion!
